
title: Amirpasha.me
page-top-title: Amirpasha.me
top-section-bg-text: The Climate [Codex](https://open.spotify.com/track/6ttYF5VadzTssGV2i1Q08T?si=87b682a40c1a4697)
home-subtitle: Amirpasha Mozaffari
copyright-text: '&copy; Amirpasha Mozaffari 2023. All Rights Reserved.'
